name: hackathon-back
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: e0eb17acb14e358ab786bb64149fc9f6
      POSTGRES_DB: banco
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
  
volumes:
  db_data: