name: hackathon-back
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 74913518abbc8cd9433ac8e0b27271af
      POSTGRES_DB: hackathon_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
  
volumes:
  db_data: