# Generated by Django 5.1.3 on 2024-11-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentsavemodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='paymentsavemodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymentsavemodel',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='paymentsavemodel',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='paymentsavemodel',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='paymentsavemodel',
            name='id',
            field=models.CharField(max_length=155, primary_key=True, serialize=False, unique=True),
        ),
    ]
