# Generated by Django 5.1.3 on 2024-11-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_django_app', '0002_alter_paymentsavemodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsavemodel',
            name='time_approved',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.RemoveField(
            model_name='credit',
            name='payment',
        ),
        migrations.AddField(
            model_name='credit',
            name='payment',
            field=models.ManyToManyField(related_name='credit_payment', to='credit_django_app.paymentsavemodel'),
        ),
    ]
