# Generated by Django 5.1.3 on 2024-11-28 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_django_app', '0001_initial'),
        ('credit_django_app', '0003_paymentsavemodel_time_approved_remove_credit_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsavemodel',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='campus_django_app.student'),
        ),
    ]
