# Generated by Django 5.1.3 on 2024-11-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_django_app', '0004_paymentsavemodel_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsavemodel',
            name='date_created',
            field=models.DateField(blank=True, max_length=155, null=True),
        ),
    ]
