# Generated by Django 5.1.3 on 2024-11-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_django_app', '0006_alter_credit_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='payment',
            field=models.ManyToManyField(blank=True, null=True, related_name='credit_payment', to='credit_django_app.paymentsavemodel'),
        ),
    ]
