# Generated by Django 5.1.3 on 2024-11-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_django_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
