# Generated by Django 5.1.3 on 2024-11-27 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus_django_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryRestrictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garnish', models.CharField(blank=True, max_length=255, null=True)),
                ('main_course', models.CharField(blank=True, max_length=255, null=True)),
                ('dessert', models.CharField(blank=True, max_length=255, null=True)),
                ('juice', models.CharField(blank=True, max_length=255, null=True)),
                ('dietary_restrictions', models.ManyToManyField(blank=True, to='cafeteria_django_app.dietaryrestrictions')),
            ],
        ),
        migrations.CreateModel(
            name='TurnstileEntrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('payment', models.BooleanField(default=False)),
                ('max_students', models.IntegerField(default=300)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='campus_django_app.student')),
            ],
        ),
    ]
