# Generated by Django 5.1.3 on 2024-11-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteria',
            name='lunch_price',
            field=models.FloatField(default=0.0),
        ),
    ]
