# Generated by Django 5.1.3 on 2024-11-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_django_app', '0002_menu_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dietary_restrictions',
            field=models.ManyToManyField(blank=True, null=True, to='cafeteria_django_app.dietaryrestrictions'),
        ),
    ]
