# Generated by Django 5.1.3 on 2024-11-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_django_app', '0003_alter_menu_dietary_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='vegetarian_option',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
