# Generated by Django 5.1.3 on 2024-11-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('free_afternoons', models.JSONField(blank=True, null=True)),
                ('free_lunch', models.BooleanField(default=False)),
            ],
        ),
    ]
