# Generated by Django 5.1.3 on 2024-11-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterField(
            model_name='classname',
            name='free_afternoons',
            field=models.JSONField(blank=True, default={'friday': False, 'monday': False, 'saturday': False, 'sunday': False, 'thursday': False, 'tuesday': False, 'wednesday': False}, null=True),
        ),
        migrations.AlterModelTable(
            name='campus',
            table='company',
        ),
    ]
