# Generated by Django 5.1.3 on 2024-11-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_django_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='free_afternoons',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
