# Generated by Django 5.1.3 on 2024-11-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_django_app', '0002_alter_campus_options_alter_classname_free_afternoons_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name_plural': 'campuses'},
        ),
        migrations.AlterModelTable(
            name='campus',
            table='campus',
        ),
    ]
